import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";


import NavBar from "./components/navigation/navbar";
import { Container } from "@mui/material";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Kawin Cheong",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar />
        <Container maxWidth={false}
          sx={{
            height: '100%',
            margin: 0,
            padding: 0,
            backgroundColor: '#241f1f'
          }}>
          {children}
        </Container>
      </body>
    </html>
  );
}
